### ISSUE TITLE
The GUI page got too many web audio objects ,then stuck

### ISSUE THREAD

**Issue by Jinglouyan** [alexa/alexa-smart-screen-sdk#126]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I say "tell me a joke", the GUI page show a joke with playback. Then I use the chrome devtool to analysis to see the memery , the count of web AudioContext and web AudioDestinationNode are increasing every time. After about 1,000 times , the GUI page got stuck.
![image](https://user-images.githubusercontent.com/28914530/157147868-0155450a-3913-46b7-afb2-823c738c1428.png)
![image](https://user-images.githubusercontent.com/28914530/157147999-3f9aba3f-fb98-4385-a345-c03dc1eeb6ab.png)
![image](https://user-images.githubusercontent.com/28914530/157148032-25f372e5-d141-4e53-beb4-fcdd3eed2c66.png)

## What is the expected behavior?

The web audio objects should be released after used,do not increase every time .The GUI page should works well ,even after 1,000 times.
## What behavior are you observing?

Web audio object were not be released
## Provide the steps to reproduce the issue, if applicable:

say "tell me a joke" , and duplicate
### What version of the AVS Device SDK are you using?
      <2.8.0>

### Tell us what hardware you're using:
- [ ] Other - tell us more:Linux TV

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is reproducible on the AVS Device SDK SampleApp.

###More information
alexa smart screen sdk : 2.8.0
apl-client-library:1.7.2
apl-core-library:1.7.1
avs-device-sdk:1.25.0

**Comment by Jinglouyan** [comment]
@powj If it do have problems , what could I do to remedy it without change version without changing version
Looking forward to your reply , thanks.

**Comment by powj** [comment]
Hi @Jinglouyan , thank you for providing the reproduction steps. 

After investigating I believe that the problem is coming from the [apl-client-js](https://github.com/alexa/apl-client-library/tree/main/apl-client-js) library which we depend on for rendering APL. It occurs specifically with 'tell me joke' because this utilizes APL SpeakItem which is rendering audio through the browser.
I have brought this to the attention of that team, however at the moment I am unable to provide any workarounds as further investigation is needed to understand root cause the issue.

**Comment by Jinglouyan** [comment]
@powj Thanks for your reply, I will continue to focus on this issue.
