### ISSUE TITLE
Video source can't be played

### ISSUE THREAD

**Issue by zhaokai3000** [alexa/alexa-smart-screen-sdk#140]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The cloud may return a video source for some voice command. The smart screen keeps buffering the video for very long time until timeout and returns to default page.

## What is the expected behavior?

The video is played.

## What behavior are you observing?

The smart screen keeps buffering the video for very long time until timeout and returns to default page.

## Provide the steps to reproduce the issue, if applicable:

1, say "Alexa, what's the latest news between US and Europe?"
2. Alexa says "Here's the story", the smart screen start buffering the video source but can't start video playback.

### What version of the AVS Device SDK are you using?
      <2.9.2>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

I tryed chrome and firefox, both have the same issue.

By the way, I wonder if there's a way to let alexa know that the device doesn't support video playbacks.
I tried to set interactionModes.video in the smart screen config file to "UNSUPPORTED", but seems alexa still try to play the video source.
<img width="782" alt="1661156686640" src="https://user-images.githubusercontent.com/16895712/185875034-69720fe7-56e8-4256-9c5d-9f7c89cd4909.png">

**Comment by dtpancha** [comment]
Hi @zhaokai3000, after investigation, we have determined that the issue with video playback is likely a skill issue rather than a Smart Screen SDK issue. As for the issue of setting interactionModes.video to "UNSUPPORTED," the expected behavior according to our documentation [here](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-video.html#devices-that-dont-support-video) is that a blank screen will appear instead of the video. Alternatively, certain skills may check for video support beforehand. It is up to each individual skill to handle this situation. We will follow up with this skills team internally. Please let us know if you have any other questions. Else, we will resolve this issue as it is not specifically a Smart Screen SDK bug.
