### ISSUE TITLE
Flash black screen when resume audible book

### ISSUE THREAD

**Issue by oscar1372** [alexa/alexa-smart-screen-sdk#39]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I test audible book and pause / resume it.
It will show black screen suddenly. The behavior is difference with echo show.

## What is the expected behavior?

It will keep screen and only change pause/resume icon

## What behavior are you observing?

It shows black screen suddenly and refresh.

## Provide the steps to reproduce the issue, if applicable:

1. Play audible book
2. Pause
3. Resume

### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment]
Hi @oscar1372,
 Thanks for reaching out. We are able to reproduce this defect at our end. We are actively investigating the issue and will update you with the status.
 
Thank you for your contribution to the Alexa Smart Screen SDK!
Varun

**Comment by VaruPan** [comment]
Hi @oscar1372,
I have an update on this issue. The reason why we see a black screen is because Alexa Smart Screen SDK is re-rendering the audio player card when resumed. This is done because SDK is observing a change in the metadata which triggers a refresh. We have informed the audible team and hope this gets addressed soon.

Once again, thank you for your contribution to the Alexa Smart Screen SDK!
Varun
