### ISSUE TITLE
Question about v2.3.0 GuiConfigSample_TvOverlayLandscape.json dialog not support

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#56]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I found there one little problem about v2.3.0
When I use RPi4 to start smart screen sdk 2.3.0. Ask weather or wiki information.
It seems there could enter into speaking mode.
Here is my start command:
./modules/Alexa/SampleApp/src/SampleApp \
-C ../../config/AlexaClientSDKConfig.json_1.20.0 \
-C ../../config/ss-sdk/2.3.0/SmartScreenSDKConfig.json \
-C ../../config/ss-sdk/2.3.0/GuiConfigSample_TvOverlayLandscape.json \
-L DEBUG0

If I remove the GuiConfigSample_TvOverlayLandscape.json the behavior is normal.

./modules/Alexa/SampleApp/src/SampleApp \
-C ../../config/AlexaClientSDKConfig.json_1.20.0 \
-C ../../config/ss-sdk/2.3.0/SmartScreenSDKConfig.json \
-L DEBUG0

I found there is one difference about "dialog": "SUPPORTED" which is "id": "tv_overlay". 
Could you help to check does it is parameter error?

https://github.com/alexa/alexa-smart-screen-sdk/blob/4e7b7a6da9a683c67c3428720dbd58f467cd2c27/modules/GUI/config/guiConfigSamples/GuiConfigSample_TvOverlayLandscape.json#L83

https://github.com/alexa/alexa-smart-screen-sdk/blob/4e7b7a6da9a683c67c3428720dbd58f467cd2c27/modules/GUI/config/SmartScreenSDKConfig.json#L110

## What is the expected behavior?

Dialog perform normally

## What behavior are you observing?

Dialog not trigger when weather information show.

## Provide the steps to reproduce the issue, if applicable:

1../modules/Alexa/SampleApp/src/SampleApp \
-C ../../config/AlexaClientSDKConfig.json_1.20.0 \
-C ../../config/ss-sdk/2.3.0/SmartScreenSDKConfig.json \
-C ../../config/ss-sdk/2.3.0/GuiConfigSample_TvOverlayLandscape.json \
-L DEBUG0

2.Ask 'what's the weather in Taipei'

### What version of the AVS Device SDK are you using?
     AVS Device SDK: <1.20.1>
     APL core library: <1.4.1>
     Alexa smart screen SDK: <2.3.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [*] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by lynx-arul** [comment]
Hi thanks for reaching out. 
Please note that when running the SampleApp you only required a single JSON file for device SDK and a single JSON file for SmartScreen SDK. In your case it should be 

```
./modules/Alexa/SampleApp/src/SampleApp
-C ../../config/AlexaClientSDKConfig.json_1.20.0
-C ../../config/ss-sdk/2.3.0/SmartScreenSDKConfig.json (the one inside modules/GUI/config/SmartScreenSDKConfig.json)
-L DEBUG0
```

or

```
./modules/Alexa/SampleApp/src/SampleApp
-C ../../config/AlexaClientSDKConfig.json_1.20.0
-C ../../config/ss-sdk/2.3.0/GuiConfigSample_TvOverlayLandscape.json (inside modules/GUI/config/guiConfigSamples/GuiConfigSample_TvOverlayLandscape.json)
-L DEBUG0
```

If you have multiple JSON file it'll pick the last one.

There is a [md file](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/SmartScreenSDKConfig.md) which goes over the configuration.

Having said that it looks like you want to have the Overlay experience, this is visible on the TV's landscape configuration. This is a sample reference configuration file, feel free to change the DIALOG from UNSUPPORTED to SUPPORTED. The reason we left it unsupported is because when your watching TV and you have an overlay pop-up you do not want audio to overlap your TV show. You can see that it's only done on the OVERLAY card as you mentioned based on the ID and not on the fullscreen experience (Ie. if you ask for "Alexa Open Kayak" audio should be there). 

I hope this help, please do reopen this ticket if your still having issue.

Thanks
