### ISSUE TITLE
Smart Screen SDK performance is too slow at X86 machine

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#9]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I follow this instruction to build x86 ubuntu vesion smart screen sdk 2.0.1.
I try to use firefox(69.0.2 (64-bit))/chromium-browser(78.0.3904.108).
The performance is too slow(It need to take more than 5-10 sec to show UI)
Sometime it couldn't show weather display card.
Here is my log about running smart screen sdk as below
[sampleapp_ss.log](https://github.com/alexa/alexa-smart-screen-sdk/files/3926865/sampleapp_ss.log)
The video is as below
https://vimeo.com/user105924617/review/377537751/25ee87777e

## What is the expected behavior?

It should show up UI like this demo(< 3 sec)
https://www.youtube.com/watch?v=84x8I6XVF4I

## What behavior are you observing?

The performance is too slow(It need to take more than 5-10 sec to show UI. Sometime it will delay to show UI until next command running)

## Provide the steps to reproduce the issue, if applicable:

1.Run browser with 
2.Run smart screen sdk
./modules/Alexa/SampleApp/src/SampleApp -C ~/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json -C ~/sdk-folder/alexa-smart-screen-sdk/modules/GUI/config/guiConfigSamples/GuiConfigSample_TvOverlayLandscape.json -L DEBUG0 2>&1 | tee sampleapp_ss.log
3.Push a & say what's weather in Taipei.
4.Push a & say play music from tune-in

### What version of the AVS Device SDK are you using?
      <1.15.0>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by eeduwj** [comment]
Your Vimeo video seems not to be accessible.

I've the sample app running on Ubuntu as well (Ubuntu 18.04.3 and Google Chrome 78) and the Taipei weather shows up in less than 2.5 seconds. I started my stopwatch when the Alexa sample app console output was done with "THINKING" and started "SPEAKING" and stopped the watch when the GUI appeared in the browser.

Launching "tune-in" took around 5 seconds but that seems to include figuring out what the play. The GUI appears on the screen around 2 seconds after the audio starts playing.

My platform is an old industry PC (Hystou PC, Intel i5-3317U, 1.7 GHz x 2) which scores 18181 in the Codeload part of the Octane 2.0 benchmark (https://chromium.github.io/octane/). My work laptop scores around 30000.

It might be slower for you because you build the JetPack javascipt bundle in "development" mode and not in "production". In order to change that go to "modules/GUI/js/webpack.config.js" and after the "module.exports" line you need to change "mode: 'development'", into “mode: 'production” and remove the "devtool: 'inline-source-map'" line. That reduces the bundle.js file size.

**Comment by yuan0258** [comment]
I upload video to YouTube link
https://youtu.be/tQUjKxg2KyE

**Comment by eeduwj** [comment]
I see, yes that's very slow.
Could it be a slow Internet connection (low average bandwidth and/or high latency)?
It took around 18 seconds until the music started playing. That might be since it took a lot of time to buffer enough data to start playing. I tried it on my computer and the music started in less than 4 seconds. If the audio is already so slow then the visual parts would likely be slow as well.

**Comment by yuan0258** [comment]
@eeduwj,
My PC platform is Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz x 4 which scores is 33680.
I already try to build JetPack with those config. It seems it could shrink main.bundle.js size from 4.3M to 668K. But the behavior is same with old one.
module.exports = {
    mode: 'production',
    //mode: 'development',
    //devtool: 'inline-source-map',
    context: SRC,
    entry: {
        'main': './main.tsx'
    },

**Comment by yuan0258** [comment]
@eeduwj ,
For ask weather case. The alexa cloud already replay audio but I doesn't see UI comes up immediately.
How could I know about when smart screen sdk get webpage from cloud?

**Comment by eeduwj** [comment]
Your PC is fast enough unless some other process is taking up too many resources. I recommend starting "System Monitor" and monitoring the CPU history.

668KB for main.bundle.js is good as well.

Finding out when the  Smart Screen SDK gets the visual elements for the webpage from the Amazon cloud can be done with Wireshark. But the HTTPS2 connection is encrypted. You can edit the file "~/.bash_profile" and add "export SSLKEYLOGFILE=~/.ssl-key.log" and then point Wireshark to this file. Then you can see (with times) the decrypted HTTP2 data transfer between the Smart Screen SDK and the Amazon cloud. That should tell you if the data is slow to arrive at your PC or if the delay is on your PC.

**Comment by yuan0258** [comment]
I use those command to capture http2 connection
FILE_URL="file://$(pwd)//modules/GUI/index.html"
chromium-browser --ssl-key-log-file=./ssl-key.log "$FILE_URL" &

./modules/Alexa/SampleApp/src/SampleApp -C ~/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json -C ~/sdk-folder/alexa-smart-screen-sdk/modules/GUI/config/guiConfigSamples/GuiConfigSample_TvOverlayLandscape.json -L DEBUG0 2>&1 | tee sampleapp_ss.log

Here is my wireshark packet.
[eth0_localhost_wireshark.tar.gz](https://github.com/alexa/alexa-smart-screen-sdk/files/3942520/eth0_localhost_wireshark.tar.gz)

I only ask what's weather in Taipei
It seem the packet is normal get from alexa cloud. But it couldn't render in the meantime(See localhost_wireshark.pcapng)

**Comment by eeduwj** [comment]
I had a look at your network capture file (eth0.pcapng). Unfortunately I can't see when the images for the weather are being received from the network. I can't see the decrypted, uncompressed data. But I can see at least the TLS data.
The interaction seems to start at around 3 seconds and there is a chunk of data of around 112 KB arriving between 10.73 sec and 11.49 sec and another chunk of data of around 199 KB between 17.10 sec - 17.6. If the latter data is for the visuals of the Taipei weather it would explain why the weather is displayed so late. My guess is a slow or otherwise problematic (Firewall, proxy, router) Internet connection.

**Comment by yuan0258** [comment]
Our network is using Symmetric NAT. 
Does it will impact speed of smart screen sdk to get content from internet?

**Comment by yuan0258** [comment]
@lynx-arul 
I found it's network problem. 
When I use cell phone 4G network to share to my PC.
The performance is good.
Maybe there is some network firewall will block this.
Those log is I capture by different network setting.
It seems download APL document take about 6 sec in ethernet 
[sampleapp_ss_DEBUG9_Fail_by_ethernet.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/4028707/sampleapp_ss_DEBUG9_Fail_by_ethernet.zip)
[sampleapp_ss_DEBUG9_OK_BY_4G.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/4028708/sampleapp_ss_DEBUG9_OK_BY_4G.zip)

**Comment by lynx-arul** [comment]
Great thanks a lot for letting us know. 
I'll go ahead and close this ticket.
