### ISSUE TITLE
How to dynamically adapt the rotating screen with GUI

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#92]
The screen width and height of my device is 1280 * 800. Then, after rotating the screen, the screen width and height are 800 * 1280. When I said alexa tell my a joke, then there was still no adaptation. Is there any way to solve this problem?

**Comment by powj** [comment]
Hi @gaoseng,

The reference GUI currently does not support screen resizing or rotation, adding support for this use case is possible however it will require a number of code changes and the end result may not be ideal due to limited APL support for viewports of this size.

If you did wish to try this anyway you would need to do the following:
* In your SmartScreenSDK configuration file update the [VisualCharacteristics configuration](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/SmartScreenSDKConfig.md#visual-characteristics-parameters) to add Alexa.Display.Window templates for both the 1280 * 800 screen and the 800 * 1280 screen. You will need both configurations so that the correct template can be referenced in the WindowState context.
* Modify the GUI JS application so that upon rotation the WindowState context is updated to report the correct template, this can be done using the [deviceWindowState](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/SDK-GUI-API.md#devicewindowstate) API
* Ensure that the correct APL Viewports are created by updating [rendererWindowConfigs](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/app.tsx#L578)

As I previously mentioned, even after doing these steps you may find that many APL skills do not provide a good experience as they have not been tested against this viewport configuration.

**Comment by gaoseng** [comment]
> Hi @gaoseng,
> 
> The reference GUI currently does not support screen resizing or rotation, adding support for this use case is possible however it will require a number of code changes and the end result may not be ideal due to limited APL support for viewports of this size.
> 
> If you did wish to try this anyway you would need to do the following:
> 
> * In your SmartScreenSDK configuration file update the [VisualCharacteristics configuration](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/SmartScreenSDKConfig.md#visual-characteristics-parameters) to add Alexa.Display.Window templates for both the 1280 * 800 screen and the 800 * 1280 screen. You will need both configurations so that the correct template can be referenced in the WindowState context.
> * Modify the GUI JS application so that upon rotation the WindowState context is updated to report the correct template, this can be done using the [deviceWindowState](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/SDK-GUI-API.md#devicewindowstate) API
> * Ensure that the correct APL Viewports are created by updating [rendererWindowConfigs](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/app.tsx#L578)
> 
> As I previously mentioned, even after doing these steps you may find that many APL skills do not provide a good experience as they have not been tested against this viewport configuration.

Thanks ! Now I adjust the Scale to achieve adaptation,
